# Generated by Django 4.1.7 on 2023-02-22 05:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("feeds", "0002_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="feed",
            old_name="Author",
            new_name="user",
        ),
    ]
