# Generated by Django 4.1.7 on 2023-02-22 05:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("reviews", "0003_rename_reviewer_review_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="review",
            name="feed",
        ),
    ]
