# Generated by Django 4.1.7 on 2023-02-23 01:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("feeds", "0003_rename_author_feed_user"),
        ("reviews", "0004_remove_review_feed"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="feed",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to="feeds.feed",
            ),
            preserve_default=False,
        ),
    ]
